### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by lvmajor** [mgildea/Multi-Step-Form-Js#1]
Hi there, I really appreciate this little library you put up to go along the jquery unobtrusive validation.

I would have an enhancement request, it could be really nice if users could press enter in a text field and only submit the partial form they are working on instead of submitting the whole form. 

I know I can simply prevent form submission by adding a listener on "enter" keydown event  but I wonder if there would be a better solution. 

What I do right now is I use the said event listener and block enter keydown from submitting form. I instead trigger the "next" button so it only submits the actual part I'm working on. Then on the last page I figure out there is no other msf-view section and only then I trigger the submit button. 

Would you have any better idea for this behavior or do you consider it as useless/bad practice to block form submission on "enter"?

Thanks in advance for your consideration!

**Comment by mgildea** [comment]
I see what you mean; so when a user is not on the final step when they hit enter it doesn't attempt to actually submit the form to the server but attempts to move to the next step instead.  This makes sense; I'll add that soon...maybe today or tomorrow.

Good idea.  Thanks for your support.

**Comment by lvmajor** [comment]
Nice to see it will be implemented! Thanks for that and for the nice work you've done so far :)

**Comment by mgildea** [comment]
added this functionality with version tag 0.0.8.  Enter key is intercepted if not in the final view and simply acts as the user clicking the next button.
