### ISSUE TITLE
How to validation Second Step

### ISSUE THREAD

**Issue by praphat** [mgildea/Multi-Step-Form-Js#10]
How to validation Second Step and ... ?
$(".msf:second").multiStepForm({
        activeIndex : 0,
        hideBackButton : false,
        validate: {
            rules : {
                name : "required",
                email : {
                    required : true,
                    email : true
                    }
                }
            }
 });

**Comment by mgildea** [comment]
I'm not sure I understand what you are asking... can you clarify a little?

**Comment by praphat** [comment]
I want validate on next step ?


First Step >>>>>>
$(".msf:first").multiStepForm({
activeIndex : 0,
hideBackButton : false,
validate: {
rules : {
name : "required",
email : {
required : true,
email : true
}
}
}
});

**Comment by praphat** [comment]
$(".msf:eq(1)").multiStepForm({
.....
});

not working.

**Comment by praphat** [comment]
You understand ask ?

**Comment by mgildea** [comment]
not really.  did you follow the setup instructions in the README?  you should only have to call the function once during initialization on the element with class "msf".  Then there should be a child element with class "msf-content", which contains children elements each with class "msf-view".  All of your form fields should be in these "msf-view" elements.  Validation is done with jquery-validation, no further calls are necessary per page/view.

If you want to provide some details if you continue to have problems that could be helpful.

**Comment by praphat** [comment]
ok thank you ,
