### ISSUE TITLE
any way to add logic to a step

### ISSUE THREAD

**Issue by csbbosen** [mgildea/Multi-Step-Form-Js#11]
Is there any way to add logic to a step. If a radio button is clicked, skip to a different panel other than the next panel.

**Comment by mgildea** [comment]
I think there can be. I need to publish a small update to return the form object after being instantiated (can't believe I didn't already have this in the code).  Then you should be able to access the functions within to conditionally move around between steps.  I'll get to this soon

**Comment by mgildea** [comment]
the code now returns the form object after instantiation, so you should be able to access the functions for navigating to different views or validating views.  Hopefully, this access will help you do what you need to do.  If not post another issue and maybe we can add some better conditional functionality to whether a view is shown or validated.
