### ISSUE TITLE
Validation Issue

### ISSUE THREAD

**Issue by ghost** [mgildea/Multi-Step-Form-Js#15]
Hello,

I have a problem with validation. It's validating only first rule and ignoring others...

In the example below it's validating only field with name of "first" and ignoring all others.
```

    $(".msf:first").multiStepForm({
        activeIndex: 0,
        allowClickNavigation: true,
        allowUnvalidatedStep: false,
        hideBackButton: false,
        validate: {
            rules: {
                first: {
                    required: true,
                    digits: true
                },
                second: {
                    required: true,
                    digits: true,
                    maxlength: 5
                },
                third: "required"
            }
        }

    });
```

Is it just me or there is a problem with the plugin?

Regards

**Comment by mgildea** [comment]
I don't think its the plugin, I just pass the validation rules along to jquery validation.  Are these hidden inputs fields?

**Comment by ghost** [comment]
No, normal input fields. I will keep playing around to find out what's causing the issue.

Regards

**Comment by mgildea** [comment]
do you have the same problem if you define the validation rules via data attributes instead of the json object?

**Comment by ghost** [comment]
Validation using data attributes works fine.
