### ISSUE TITLE
Any idea how to skip a step?

### ISSUE THREAD

**Issue by souldesigns** [mgildea/Multi-Step-Form-Js#16]
Hi,
for example if I wanted to directly jump to the 3rd step in your example form here: http://www.bestjquery.com/?tLERh8Pq

Is there a way to jump to the third or Nth step of the process with a button / <a> tag?

thanks !

**Comment by mgildea** [comment]
Yes this is doable:

you can use some combination of the _allowUnvalidatedStep_ and _allowClickNavigation_ options

see the description of these options in the README.

you should be able to do something like this:

```
//this allows you to access subsequent steps without the previous ones being 100% validated.
var msf =  $(".msf:first").multiStepForm({
        allowUnvalidatedStep : true
});

//setup your event handler and call 
msf.setActiveView(2);


```
