### ISSUE TITLE
Vulnerability detected by npm audit

### ISSUE THREAD

**Issue by lvmajor** [mgildea/Multi-Step-Form-Js#18]
Because Multi-Step-Form-Js has a dependency on JQuery ^2.2.0, npm audit reports a XSS vulnerability. 
Would there be any reason not to update dependency to version 3.3.1?

**Comment by mgildea** [comment]
I don't see any reason not to upgrade the jquery version.  I can try and get to it soon.  Do you have any interest in making that upgrade and submitting a pull request?
