### ISSUE TITLE
Possible enhancement request: Progress notification event

### ISSUE THREAD

**Issue by lvmajor** [mgildea/Multi-Step-Form-Js#2]
Hey there, me again :) 

I thought it could be nice to add an option that lets us use a progress bar along with the current icons. Then when passing to the next "page", we could simply modify the progress bar's value according to the current page we're in.

I will try to fiddle something up and maybe propose a PR if you think this could be a nice feature to have.

Another possibility could simply be to trigger an event in your js which contains the current "page" and the total page number so that anyone can use this event to modify the progress bar value as he wants....

**Comment by mgildea** [comment]
included in PR #3
