### ISSUE TITLE
Jumping to specific step.

### ISSUE THREAD

**Issue by AllenXavier** [mgildea/Multi-Step-Form-Js#26]
I want to know if we can make separate buttons to jump to a specific step. (in my example at the end of the form there should be a clickable overview separate from the steps at the top.

I have tried using the following functions:

  $('.js-mfs-navigate-2').click(function() {
    $('.msf:first').setActiveView(2);
  });

---------------------------

$('.js-mfs-navigate-2').click(function(event, data) {
    $.tryNavigateToView(data.currentIndex, 2);
  });

Any help would be greatly appreciated.

<img width="2060" alt="Screenshot 2020-12-23 at 12 09 14" src="https://user-images.githubusercontent.com/44436430/102990602-f0b6ac80-4517-11eb-96d3-167c087f555b.png">

**Comment by lvmajor** [comment]
Its been a while since I looked at this but here ara couple quick things that come to my mind.
1. Did you initialize with the option `allowClickNavigation : true`
2. If so, you could simply simulate the click on the corresponding "MSF-step" button when clicking on your additional buttons.

**Comment by AllenXavier** [comment]
@lvmajor You are a legend, had not even thought about doing it like that, thanks a lot man.

For people interested this is the eventual code, where step-2 is a class give to that specific msf-step

$('.js-mfs-navigate-2').click(function() {
    $('.step-2').trigger('click');
  });
